angular.module('app')
    .config(function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise('/home');
        $stateProvider
            .state('home',{
                url:'/home',
                templateUrl:'home/home.html',
                controller:"HomeCtrl"
            })
            .state('profile',{
                url:'/profile',
                templateUrl:'profile/profile.html',
                controller:"profileCtrl"
            })
            .state('profile.aboutTab',{
                url:'/aboutTab',
                templateUrl:'tabs/aboutTab.html'
            })
            .state('profile.friends',{
                url:'/friends',
                templateUrl:'tabs/friends.html'
            })
            .state('profile.contact',{
                url:'/contact',
                templateUrl:'tabs/contact.html'
            })
            .state('profile.photos',{
                url:'/photos',
                templateUrl:'tabs/photos.html'
            })
            .state('about',{
                url:'/about',
                templateUrl:'about/about.html',
                controller:"AboutCtrl"
            });
    });
